# spit out a txt of html code to insert


# Fall 2023
# pegasus, cashless-society, tech-gap, foreign-investment, japan, novo-nordisk, space-privitization
pegasus = {
    'edition':'fall-2023',
    'title':'Pegasus: The Silent Threat to Digital Democracy',
    'sh':'p', # shorthand 
    'img_dir':'pegasus',
    'content':[
        ("p", ""),
    ],
}

tech = {
    'edition':'fall-2023',
    'title':'The Widening Tech Gap: Reshaping Canada’s Tech Future',
    'sh':'tg', # shorthand 
    'img_dir':'tech-gap',
    'content':[],
}

foreign = {
    'edition':'fall-2023',
    'title':'The Double-Edged Sword of Foreign Investment: Unveiling the Cynicism of Economic Rebuilding',
    'sh':'f', # shorthand 
    'img_dir':'foreign',
    'content':[],
}

japan = {
    'edition':'fall-2023',
    'title':'Japan’s Corporations: A Path to Prosperity',
    'sh':'cs', # shorthand 
    'img_dir':'japan',
    'content':[],
}


cashless = {
    'edition':'fall-2023',
    'title':'From Dollars to Digits: Navigating the Shadows of a Cashless Society',
    'sh':'cs', # shorthand 
    'img_dir':'cashless',
    'content':[],
}

novo = {
    'edition':'fall-2023',
    'title':'GLP-1: Novo Nordisk’s Gain, Denmark’s Risk',
    'sh':'nn', # shorthand 
    'img_dir':'novo-nordisk',
    'content':[],
}

space = {
    'edition':'fall-2023',
    'title':'Space: The Misguided Promise of Privatization',
    'sh':'sp', # shorthand 
    'img_dir':'space',
    'content':[],
}



# Fall 2022

crisis = {
    'edition':'fall-2022',
    'title':'The Crisis of Greed: Behind the Scenes of the Russian-Ukrainian War',
    'sh':'c', # shorthand 
    'img_dir':'crisis',
    'content':[
        # s for subtitle, p for paragraph, i for image
        ("p", "When wars are directly contributing to lining the pockets of those at the top, it stands to question the motives for starting and continuing wars in the first place."),
        ("s", "Introduction"),
        ("p", "In early 2022, tensions started to peak between Russia and Ukraine. As the world's eyes turned from COVID-19 to the rising conflict in the East, more and more corporations started to pledge their support for Ukraine by pulling out of Russia and ceasing business with the Russian people. McDonald's said it would temporarily shut down its 850+ restaurants in Russia, while Starbucks also said that its 100 coffee shops in the country would close their doors."),
        ("p", "L'Oréal and Estee Lauder both closed shop and ceased online sales to the country, with Estee Lauder in particular losing one of their most profitable markets. Manufacturers such as Nestle, Mondelez, and Procter & Gamble halted investment in Russia but said they would continue providing essentials. The reason behind many of these decisions was to detract from the Russian economy and take a public stance on the war. Statements released had similar reasoning along the lines of \"shareholders will not stand for the continued generation of profits from Russia\"."),
        ("s", "Losses"),
        ("p", "One would think that this is a noble thing to do. The amount of business lost for these companies was astronomical, especially with the combined effects of the COVID-19 recession from just before. Foreign companies that halted operations in Russia or pulled out completely have incurred losses of more than $240 billion in total since the end of February 2022. A whopping total of $70 - $90 billion was lost on the very first day of the Russia/Ukraine war alone.  "),
        ("i", "c-1"),
        ("p", "Surely this amount would cripple the Russian economy, right? However, this seems to be the opposite of true. As a result of new closures, rich businessmen and high net worth individuals started buying shuttered locations and establishing Russian-owned chains in their place.  For instance, when McDonald's stopped operating in Russia in February (and fully exited the country by May), Siberian mining oligarch Alexander Govor bought the large majority of locations and converted them into a new Russian burger chain called Vkusno i tochka (meaning \"Tasty and that's it\"). Similarly, old Starbucks locations are now being converted into “Stars Coffee” by its new owners, Pro-Putin rapper Timur Yunusov (Timati) and restaurateur Anton Pinskiy."),
        ("i", "c-2"),
        ("p", "Russia once housed the world's busiest McDonalds in Pushkin Square, opened during the Soviet era. This was a powerful symbol of Western influence and global unity, bridging the gap between past and present. Fast forward to 2022, McDonald's write-off from exiting Russia will be between $1.2 billion to $1.4 billion. Just closing its restaurants for the first few weeks  in Russia hit earnings significantly, costing them $127 million that quarter. Now, the old locations are once again a symbol of Russian nationalism, with new Russian corporations taking over and further bolstering the Russian economy by keeping money flowing within the confines of their own borders. The World Bank predicted that the Russian economy will grow by 11.2% as a result of the invasion."),
        ("i", "c-3"),
        ("s", "Oligarchs"),
        ("p", "It may be surprising to learn that what happened here is not unique. The oligarchs of today's day and age draw many parallels to the powerful and wealthy boyar class of late-medieval Muscovy (present day central Russia). Historian Edward L. Keenan described boyars as “the top rung of the aristocracy” in the 1400s, with their influence heavily ingrained in Russia's political system. Flash forward to now, Russia still has a disproportionate amount of oligarchs and higher-than-average levels of wealth disparity, both linked to the collapse of the Soviet Union in the nineties."),
        ("i", "c-4"),
        ("p", "The majority of this group of elite businessmen gained their wealth through purchasing newly privatized Soviet Union Assets. Since ownership of state assets was contested, many of these transactions happened under questionable circumstances with ex-USSR officials at a severe discount to market rate. As a result, this class has essentially become the ruling tier of Russia, owning the majority of economic assets in the nation. Not only do Russia's oligarchs have superior influence over business and economics, but they also control a large part of the country's politics, media, and governance. New policies that they influence, directly or indirectly, allow for them to continue growing their wealth at a significant advantage over others. In 1996, prominent oligarchs Roman  Abramovich, Michail Khordorkovsky, Boris Berezovsky, and Vladimir Potanin helped fund the re-election of Yeltsin (Russia's first president after Gorbachev) in exchange for favorable policies surrounding loan-for-share purchases, their predominant method of acquiring assets for cheap. These four oligarchs made up four out of the seven most powerful men in the nation, who were known as the \"seven-banker outfit\" for the incredible power and influence over Yeltsin's government. It is estimated that these 7 controlled between 50-70% of the entire Russian economy from 1996-2000.  Controlling the economic assets allows oligarchs to be front and center of any decision making party, and thus completing the cycle that cements their status."),
        ("s", "The Putin Era"),
        ("p", "When Putin was first elected in 2000, he vowed to crack down on corruption and exile certain oligarchs. In reality, the old oligarchs who remained friendly with Putin were able to continue prospering so long as they stayed out of his way politically. Many of Putin's friends and former KGB colleagues have also become newly minted oligarchs, creating a new class of silovikis, which translates roughly to \"men of force.\" Gennady Timchenko, a long time friend of Putin, is an excellent example of this. Putin granted Timchenko one of the first oil export licenses in 1991, which allowed him to co-found the oil company Gunvor in 2000. Gunvor grew to control 35% of the state's oil exports within the first few years of operation, however, until that point was still considered a “niche player” in the market due to mostly exporting Russian oil through Estonia. Gunvor's expansion really started to kick off at the tail end of the 2008 economic crisis. While the majority of Russia was struggling, Timchenko's company took over two terminals in strategic points for international exports. Meanwhile, Gunvor's subsidiary companies began expanding laterally by taking over other companies in the construction and gas sectors and seeking access to oil fields. Timchenko himself previously owned shares in and controlled numerous smaller companies, such as Waterway Petroleum and Clearlake Shipping, and the financial crisis allowed him to strengthen these positions as well. Timchenko's group took everything “virtually overnight”. Today, Gunvor is the fourth largest crude oil trader in the world and with Russia being the world's largest exporter of oil in 2021, they are in a favorable position to continue moving even higher. In 2008, Forbes estimated Timchenko's fortune at USD $2.5 billion. Today, Timchenko sits at an estimated $23.1 billion, making him the 6th richest person in Russia."),
        ("i", "c-5"),
        ("p", "In traditional Western capitalist societies, businesses only profit when they perform a service that is useful to people. People only pay for items or services that benefit them in some way. However, in Russia, the rules of the game are blurry, hidden and rewritten to the benefit of those who stand to profit the most. The country's social and political dynamics are strikingly similar to the Russian Matryoshka nesting doll. There are multiple layers of ownership, politics, and social ties that must be uncovered in in order to find the true beneficiaries of any policy or decision. Gunvor and Timchenko's success was strongly favored by the Putin administration. There was already limited competition in the energy industry (as it is considered a strategic sector) and all decisions about ownership of particular assets had to be approved by the Kremlin. Gunvor received preferential treatment in deals, negotiations, and loans that were inaccessible to “regular” firms, such as the loan worth $545 million that was granted for their 2008 terminal constructions. Gunvor would not be where it is today without Putin’s favorite aid. "),
        ("p", "So what has been seen so far? As a result of tough economic crises like wars or recessions, the rich get richer, companies get consolidated/monopolized, and citizens get less bargaining power. The oligarchs at the top continue silently winning, profiting from favorable government policies and the rapid sell-offs of assets. Meanwhile, the average Russian working-class citizens and the global economy are the ones who suffer. But what is there to do about it?"),
        ("s", "Sanctions"),
        ("p", "For the longest time, the answer was 'sanctions'. However, sanctions only seem to drive the ruling class closer together. Boris and Arkady Rotenberg, two brothers who rose to siloviki status under Putin, were first sanctioned by the US back in 2014 for their repeated participation and enabling of “Putin pet projects”. The most notable of these was their construction of the Kerch Strait Bridge, a 12-mile bridge that connected Russia with its newly-annexed territory Crimea. This bridge had heavy logistical and political complications associated with it, evident by the circumstances it was built in, however Arkady Rotenburg's company happily did it, completing the bridge in 2018. The sanctions against them ended up working in their favor, as the brothers have proved their allegiance to the Kremlin and have received even larger contacts than before through the government."),
        ("p", "Sanctioning is also simply not an easy task. Property assets are difficult to trace, as they are often held in tax havens, shell companies, or relative's names. Many luxury yachts owned by oligarchs mysteriously 'went missing' at the start of the invasion, with their last reported sightings being months or even years back. \"It's hard to say how much their wealth has suffered because we don't know how much they had,\" said Jodi Vittori, Global Politics and Security professor at Georgetown University."),
        ("i", "c-6"),
        ("p", "Sanctions also effectively punish everyone due to how interconnected the world is. In fact, sanctions often end up hurting the global economy more than the sanction targets. One example of this is when the US sanctioned billionaire Oleg Deripaska, owner of the United Co. Rusal, in 2018, due to money laundering investigations and a myriad of other charges against him. Rusal was (and still is) one of the world's leading aluminum production companies, and when he and his company counterparts were sanctioned, aluminum prices soared. The crisis only subsided after Deipaska agreed to significantly reduce ownership in the company to meet US Treasury guidelines. This is why even now, in the midst of the Russia-Ukraine crisis, many steel tycoons, fertilizer giants, and other backbone-industry oligarchs are still sanction-free. "),
        ("p", "Sanctions did not break the spirit of Russia, and they likely never will. The current class of oligarchs will not stand up  to what is going on to what is going on in the war, despite the rising sanctions piling against them. After all, they are the unofficial aristocrats of Russia, and their agreement with Putin is essentially to \"stay quiet, stay out of the way, and be handsomely rewarded\". Their loyalty is not without reason. Oligarchs like Vladimir Gusinsky and Mikhail Khodorkovsky paid the price for daring to speak their truth, and their stories rest as threats of what happens to those who cross the line."),
        ("p", "Beyond this, however, is a simple fact: war is in the best interest of (the majority of) the ruling class. Oligarchs are incentivized to want the country to go through periods of difficulty, as this allows them to continue to propagate their empireand solidify their wealth. Multinationals like McDonalds and Starbucks rapidly exiting the country doesn’t send the financial message they think it does. Rather, it creates gaps in the economy that oligarchs are all too eager to buy up and fill. Russian oligarchs have a long history of profiting off times of crisis, and unfortunately, the current socio-political structure of Russia continues to enable this."),
        ("p", "At its heart, the Russia-Ukraine war is trading human loss for capital gain. It is a battle of politics,  greed, and selfishness.  The response in the West cannot be to pull out our multinational companies or economically sanction the country, as we only hurt ourselves and make the ruling class stronger. The real root of this problem must be targeted in order to create tangible change, not just for the people of Ukraine, but for the society of Russia as well."),
    ],
}

dependency_diversification = {
    'edition':'fall-2022',
    'title':'Dependency and Diversification: Keys to Success for Single Export Nations',
    'sh':'d', # shorthand 
    'img_dir':'dd',
    'content':[
        ("s","Introduction"),
        ("p","In 1959, around 1700 billion cubic meters of natural gas were found in Holland’s Groningen region. At the time, gas prices were near their all time high and the Dutch had a relatively strong ability to harvest oil through the Nederlandse Aardolie Maatschappij (NAM), which was jointly owned by Esso and Shell. The discovery of natural gas was believed to enable the Dutch economy to grow and prosper, which it appeared to do so through the 70s: the Dutch Guilder appreciated by 16.4% between 1971 and 1977, social security benefits made up over 23% of national income versus 16.5% in 1970, and regulations were put in place establishing minimum wages, employment standards and environmental standards. The discovery of natural gas seemed to pave a road to long-term prosperity for the region."),
        ("p","By 1977, 80% of government revenue came from the natural gas. Despite the positive outlook at the time, the country began to crumble from the inside out. Industrial production had not increased during the 70s and employment in the manufacturing industry, which was once Holland’s strongest industry, declined by 16%. Corporate investment fell nearly 15%, and the proportion of people that qualified for their long-term benefits program increased from 20% in 1965 to more than 60% in 1977. Their overreliance on natural gas exports led to a dollar so strong that Holland could not sell any other goods for a reasonable price. This interior collapse of a nation, despite a positive economic image, was coined as the term “Dutch Disease”."),
        ("i","d-1"),
        ("p","At the time, Dutch Disease was believed to be caused by an overreliance on one export. However, in the time since, it appears as though many nations have found success by relying on a single export, while others have been destroyed by it. Though previously unavoidable and misunderstood, Dutch Disease plagues nations that rely solely on one export but is entirely avoidable through strong fiscal policy."),
        ("s","Modern Single-Export Nations"),
        ("p","Dutch disease introduced the concept that relying on a singular export has harmful repercussions. However, when we look at today’s economy, we see many successful and unsuccessful nations that were born out of single export reliance, with common trends arising from both sides. Oil-rich countries such as Saudi Arabia, Qatar and the UAE come to mind as nations that have been able to utilize the export they rely upon to prosper. Though diversification might be the obvious answer to their success, entering new industries is extremely challenging when a nation does not have strong leadership or direction. The leaders of these oil rich nations have chosen to do 3 main things: invest in a sovereign wealth fund, invest in strategic industries, and control their oil companies. "),
        ("p","Sovereign wealth funds (SWFs) are investment vehicles that are often funded by natural resources and are used by a nation to diversify their interests into different industries. Based on size, the UAE’s SWF is the 3rd largest, Saudi Arabia’s is the 6th largest and Qatar’s is the 9th largest globally. These SWFs invest into industries that the host country had not found success in, such as Qatar’s SWFs investments into sports and tech, or the UAE’s investments into technology and travel. This presents a unique way to avoid Dutch disease, as a nation's rising dollar affects their exports but not investments."),
        ("i","d-2"),
        ("p","The industries that these nations appear to invest most in are the tourism and business. It appears as though their main goal is to bring foreigners in and keep them there for various reasons. For wealthy businesspeople, this means giving large tax incentives to encourage the growth of tech and finance in the country. For poor migrant workers, this means cheap labor and infrastructure development. It's a way for these oil-rich countries to increase their economic complexity while not actually relying on exports, but rather being attractive destinations to visit or live in, and using their high dollar to earn greater revenue from these newcomers."),
        ("i","d-3"),
        ("p","The final piece of this puzzle is overall government control. If the government can control the oil companies and those who operate it, they can avoid issues from Dutch Disease that were akin to the nations overreliance on their oil workers. Currently, roughly half of the world's oil production comes from state-owned companies such as Sinopec, QatarEnergy, Emirates National Oil, Aramco and Kuwait Oil Company, which are all from Asia and the Middle East. This number is expected to grow over the next decade as they are entirely self-sustaining and can collaborate through OPEC: an organization made up of oil nations like Iran, Iraq, Saudi Arabia, the UAE and others around the Middle East. Having a central power in charge of a country’s main oil company ensures decisive action and a greater ability to secure a strong workforce, while ensuring that oil profits suit the nations need. After all, the rulers get rich as the nation gets rich, so it is in their best interest for oil production to continue."),
        ("s","Unsuccessful Single-Export Nations"),
        ("p","The question then arises of how any nation can be unsuccessful with one export when there are clear examples of those that have grown tremendously from their oil. Surely there is a set of examples they can follow in order to prosper from their main export? Countries today still have deteriorating economies similar to Dutch Disease due to various factors that prevent them from capitalizing on their greatest export."),
        ("p","Single export nations that are unsuccessful appear almost “forced” to be reliant on one export, not by circumstance but by outside forces. Banana republics are the perfect example of this. "),
        ("p","Banana Republics are South American nations that are reliant entirely on bananas for their economic expansion and became this way through foreign intervention. The rise of Banana Republics was mainly due to the United Fruit Company, who’s first operation in 1871 started by building a railroad through Guatemala and Honduras. After realizing that the project was not profitable and having been granted over 800,000 acres of land along the railroad, they decided to expand into banana production. With control of over 13% of the surrounding nations land mass and over 4000 workers by the 1930s, the United Fruit Company had a heavy influence over the government purely because of the profit they brought the nation. The ultimatum was simple: if the government does not comply with the United Fruit Company, they could leave the nation and deprive them of their most successful export. The most extreme case of government control came in December 1928, when the famous “Banana Massacre'' left an estimated 2000 workers dead after they were protesting their abhorrent living conditions while working in banana farms. The massacre was led out by the Columbian military who were pressured by the United Fruit Company to bring their labor back into work. The United Fruit Company had enough control of the country that they could coerce Colombian leadership to lead out a massacre on their own people, who were protesting the conditions that they were subjected to by a foreign company, just for the country to get a meager share of the profits."),
        ("i","d-4"),
        ("p","This presents the main differentiating factor in successful and unsuccessful single-export nations: whoever controls the companies controls the profits. Successful nations own their companies, such as Saudi-owned Aramco and Qatar-controlled QatarEnergy. When profits are funneled out of a poor nation by a foreign power, the living conditions in that nation do not improve and thus it is more challenging to diversify. When large companies are state-owned, investment can be made to better the nation and prosper."),
        ("p","A common argument is that the type of export is the main factor which decides if a nation will be successful or not successful. After all, while oil-rich countries such as the UAE and Qatar have thrived, banana-rich countries have suffered. Though one might argue that Banana Republics are unsuccessful because their export is less desirable in today’s economy, Nigeria has suffered in similar ways despite their main export also being oil."),
        ("p","95% of Nigeria’s exports are oil exports, which make up 40% of their total economy. The vast majority of their oil wells are owned by Shell, who “purchased” oil fields from the economy through shady-looking purchases that involved bribed government officials. Most notably, the $1.3B purchase  of OPL 245 led to $466M in the pockets of government officials. Today, the country is so reliant on the oil giant that 65% of their government revenue comes from oil. Though the relationship was initially symbiotic with Shell gaining new oil fields and Nigeria getting new infrastructure, foreign investment, labor opportunities and profits, Shell’s immense power was abused through massive oil spills (they admitted to around 250 oil spills per year from 1997-2006) and power consolidation. One of the most noteworthy acts is their devastation of Ogoniland, a 1000km  add delta that was poisoned with oil spills, which Shell paid $83M to fix despite the UNEP estimating that a $1B fund is needed to correct the environmental damage. "),
        ("i","d-5"),
        ("p","In 1994, Shell was also accused of complicity when 9 Ogoni men were protesting alongside the Movement for the Survival of the Ogoni People (MOSOP) and got arrested and executed. only $15.5M was paid to their families as settlement. These countries were taken over by companies that demanded more power and destroyed their nations by making them reliant on the exports that earned them the most profit. Dutch Disease is strong in nations that have higher dollars and labor forces that are empowered by their reliance on one export, but it is also strong in nations where their other exports are destroyed by monopolization and their labor forces are suppressed by their own governments that act as puppets to foreign conglomerates."),
        ("s","What defines success?"),
        ("p","In the times of Dutch Disease, it was believed that being reliant on one export caused nations to fail. The same was seen in the 1970s when Great Britain found oil off the coast of Scotland and they fell in a recession despite oil prices quadrupling. However, we’ve seen nations such as the UAE and Qatar become net oil exporters while successful, and net exporters such as Nigeria and Banana Republics be unsuccessful. So what causes this difference?"),
        ("p","We’ve already established that the type of export has little influence on the country's success, with some oil nations finding success and some not. The UAE and Qatar were once poor countries with exports such as fishing and farming, but were able to transform into global superpowers. Nigeria is in a similar situation to pre-oil middle eastern countries, but are still finding it difficult to progress. The main success factors lie beyond the type of export."),
        ("p","The other main idea is the possibility of collaboration. The largest oil exporters are members of OPEC, which allows these countries to control global trade of oil by setting volume mandates. If a country like Nigeria could join OPEC, it could perhaps find more success by being able to collaborate with some of the other exporters. Banana Republics could form their own type of OPEC and control global banana exports, asserting how much volume can be distributed and controlling prices as a result. However, there is one large factor that prevents this from being possible that defines the main factor which separates successful and unsuccessful single export nations."),
        ("p","The success of single export nations is solely dependent on their foreign policy and level of government control. When a nation is able to learn from the lessons of Dutch Disease and quickly expand into new industries through an investment vehicle or government spending, they are able to benefit from their profits from any export that they might rely on. This is only possible with strong foreign policy, where spending is constantly monitored and trends are understood."),
        ("i","d-6"),
        ("p","We spoke with an individual from the IMF who has studied the effects of foreign policy on the success of a nation. Through in-depth discussion and ideation, we learned that nations suffer when their economies are informal and their labor costs are too high, which pose as barriers to growth as the nation might try to create an entity to generate profit through successful exports. The defining factor between success and failure in the eyes of this individual was a country's economic framework. Countries need to control their exports, but their success is defined by much more than that: they also need to look at their education levels, their labor laws and their investments. The way forward for suffering nations is unclear, said this individual, but they must start by taking control of their resources and using their profits to encourage long term prosperity."),
        ("s","Conclusion"),
        ("p","It appears as though the goal of every single export nation is to diversify away from that export. This is seen globally through the Middle East's growth in tourism, Norway’s sovereign wealth fund and even Canada’s own pension plans that were developed from their oil sands. Dutch Disease is a condition gained from being reliant on an export for too long, and these countries are trying their best to diversify as quickly as possible in order to avoid the condition. This is simply not possible when foreign companies obtain too much share of a nation's profits and prohibits them from expanding into new industries and rather forces them to stay entirely focused on the one export that brings them the most success for their bottom line. The solution is clear: control the profits and invest them in a way where the country can avoid over reliance."),
    ],
}

digital_reccession = {
    'edition':'fall-2022',
    'title':'The Digital Recession',
    'sh':'dr', # shorthand 
    'img_dir':'dr',
    'content':[
        ("s","Introduction"),
        ("p","In the world of the autonomous, people like to believe that nothing is impossible. Most of the time, this philosophy is a good thing. The ability to build systems that can alleviate human dependencies and provide quick and efficient solutions means that society as a whole can move faster, quicker, and more efficiently. However, sometimes the world moves so quickly and with such fervor to break barriers and innovate, that it seemingly disregards the bumps along the road. Whether or not it's a product of ignorance, the smaller problems that bubble underneath the clear, undisturbed image of any form of advancement are not revealed until it's too late. "),
        ("p","Whether people want to look to the present day with the advent of new-age cryptocurrencies and their fun penchant for consumer fraud, or the very pandemic that destabilized the current economy, every major conflict has begun by distracting themselves with the obvious problems right in front of them with the sensationalization of something new and profitable. Accompanied by an unfathomable belief that they know what they are doing, it is no wonder that the root cause of these issues can be traced back to their inception."),
        ("p","When it comes to the technological bubble, the reality is that only a few people really know what’s going on and the true consequences of what’s being created. Bots and spam, which had been the bedrock of any piece of technology for decades, are part of that trend. A bump in the road for that matter is treated as unimportant. Unfortunately, we’re about to realize that’s not the case at all. Bots are not just a nuisance, and are far more dangerous weapons than we realize."),
        ("p","With automation at its peak, the infestation of bots and spam online has reached a potential point of no return. Soon the internet will begin to collapse in on itself and the line between real and fake will become impossible to differentiate. With the power to sway public opinion now so accessible to anyone with an agenda, the internet finds itself entering its own digital recession, a time of socio-political uncertainty where the world is truly at the mercy of the anonymous."),
        ("s","The Consequences of Widespread Automation and the Rise of Spam"),
        ("p","Before someone can understand why bots and spam are so dangerous, they need to first understand how they work in the first place as well as their connection to modern-day automation. Automation is the use of technology applications to minimize human input. It’s the creation and application of technologies to complete tasks with reduced human interaction."),
        ("s","Bots in general can be used for good purposes, such as search engine bots which manifest themselves as web crawlers. These can review content on websites and index them so that they show up on web searches. Copyright bots also exist and review content that violates copyright laws. Site monitoring bots frequently monitor for website metrics and any potential issues such as system outages or backlinks. In other words, bots are surprisingly a cornerstone for a lot of modern-day processes that allow the internet to function the way that it does. The real issue arises when these bots are warped and become delivery systems for the most dangerous viruses on the internet. Delivery systems we refer to as spam. "),
        ("i","dr-1"),
        ("i","dr-2"),
        ("i","dr-3"),
        ("p","The bots that can be programmed for malicious intent are referred to as “Bad Bots”. Think of it as someone who has been infected with a virus. Since bots make up over half of all web traffic, unprotected websites hosted by unqualified individuals on the internet can become a prolific target. These “bad bots” can also come in several forms. There are scraper bots that are programmed to steal content, such as pricing and product information so businesses can undermine the pricing strategies of a target. There are spam bots (which are the most common) that target community portals, and social media, and interfere with online conversations by inserting unwanted advertisements, links, banners, political agendas, etc. Finally, there are scalper bots that target ticketing websites to purchase hundreds of tickets as soon as bookings open to later resell the tickets at inflated prices."),
        ("p","All of these bots - good and bad - are possible because of the proliferation of AI  technologies to the general public. If automation is possible and easy, then so are bots. If bots are real, then it becomes impossible to tell what isn’t. These bots more than anything affect perception online. Repeatedly sharing misinformation and fake news links, leaving bad reviews on websites, creating artificially inflated support for extreme views, and skewing poll data are only a few examples of what’s possible and already happening. When this reality exists, truth on the internet means nothing. "),
        ("p","A good example of this is modern-day uses of ChatGPT. For context, ChatGPT is an open-source AI similar to Siri or Alexa, but far more advanced. If you go onto the platform and tell it to write you a  fraudulent email that can be used to “phish” someone, it will create that for you. If you tell it to build a program for you that can spam hate comments on YouTube, it will create that for you. It will do all that in milliseconds without any moral qualms. AI is only a tool, but bots are the actual weapon."),
        ("s","Weaponizing the “Botnet” and its Underground Economy"),
        ("p","Most of the misunderstanding behind these “bad bots” is that people think they are employed by groups of unrelated, and unconnected people. However, bots and spam are less random than we think and have transitioned into their own form of organized crime."),
        ("p","On most occasions, they are operated by movements of large groups who have some sort of intention to target people and distort the majority narrative online. These groups are often the homes of a “Botnet” which is a group of one or more interconnected devices that each run a bot that forms a system of bots that can "),
        ("i","dr-4"),
        ("p","collaborate to perform DDoS attacks, post spam, etc. Surprisingly though, these botnets are not a new occurrence and have been around for years. The first instance of a botnet was a trojan called Sub7 that was released in 1999, just a few years after popular good bots started becoming relevant such as the Googlebot web crawler released in 1996. A more popular example is Trojan - a bad bot that disguises itself as legitimate software and instead is designed to damage your computer, steal data, disrupt your network, etc."),
        ("p","One of the most significant botnets in history however was called Pretty Park. It was an email worm that was also released in 1999 that would come attached to emails. When executed,  it would install itself onto the system and then send email messages through the computer to the address book. It could also be used as a backdoor into the computer. For context, a worm is a type of malware whose primary function is to self-replicate and infect other computers while remaining active on infected systems. This particular worm paved the way for several major botnets that rose to prevalence in the mid-2000s such as Storm, which was one of the most aggressive pieces of malware known yet. It spread through links within messages that attempted to get users to download malware from a website.  Storm has affected an estimate of over 1 million computers to date."),
        ("i","dr-5"),
        ("s","Conclusion"),
        ("p","The prevalence of these “botnets” are evidence of the fact that they work more like an underground digital crime organization than pockets of random unconnected individuals and this makes them that much more dangerous."),
    ],
}

meta = {
    'edition':'fall-2022',
    'title':'META: An End Over Over the Horizon?',
    'sh':'m', # shorthand 
    'img_dir':'meta',
    'content':[
        ("s","Introduction"),
        ("p","This last year has proven to be considerably difficult for FANNG businesses, which were largely responsible for a majority of the economic growth in 2020 and 2021. During that period, however, Facebook made a defining choice in its business model by prioritizing Metaverse products in their business model. In October of 2021, they leaned heavily into this new segment and restructured their business entirely around it, with the most prolific change being their name change from Facebook to Meta. However, as economic policy shifted towards a more constrained environment, the company found itself ensnared in what was once its most promising venture. Recently, the Metaverse has been faltering due to the lack of regulation, fraudulent activity, and wavering demand. If this pessimistic outlook on an integral part of Meta’s expected future success doesn’t change, this may lead to a failure to realize the potential of their Metaverse investment and bring the business to its demise due to an adjacent lack of priority in their social media segment which is facing monetization and competitive headwinds. "),
        ("p","However, before we go into the company's troubling situation, it helps to know how it  got there in the first place and this requires some context."),
        ("s","The Pre-Meta Period:"),
        ("p","In its early years, Facebook was an app solely targeted to college students, but this model shifted once Facebook saw incredible traction within a short period; the app reached 1 million users in ten months. The company had a mission to connect people and communities by taking the social experience online. Over the next 14 years, growth was defined by a combination of user growth and key acquisitions which have played a defining role in their business to date. Targeted advertising became their key driver of revenue, as they provided much higher engagement metrics than traditional advertising solutions would at the time, thanks to their data collection. "),
        ("s","Beginning of the End:"),
        ("p","That brings them to a fundamental problem. What happens if people don’t want to join the platform anymore or potentially even leave? The threat of obsolescence is especially prevalent in industries experiencing intense  competition. They could fight this by acquiring businesses which complement their main platform, which worked with Instagram. Well, that's exactly what they did, and this resulted in two important events to bring them to where they are today. It first gave them the first taste of what the Metaverse had to offer through their acquisition of Oculus in 2014, and second, it began a long and winded string of antitrust issues with regulators which hindered their ability to remain acquisitive in a timely manner."),
        ("i","m-1"),
        ("p","Eight years after Facebook acquired Instagram, the Federal Trade Commission announced that they were suing Facebook for “illegally maintaining its personal social networking monopoly through a years-long course of anticompetitive conduct.” They requested an injunction to force the divestment of Instagram and Whatsapp, pitching that it occurred due to the existential threats they posed to the Facebook-Messenger monopoly. The case is on-going with a trial expected to begin sometime by the end of 2023 to 2024 which puts a potential countdown on the businesses performance.  Regulatory headwinds were further exacerbated one year later as in 2021, as a product manager at Facebook named Frances Haugen came forward and released confidential documents to whistleblow malpractice within the business. These documents revealed troubling information about both Facebook and Mark Zuckerburg, with topics including societal and political ailments inflicted in the name of profitability. The senate demanded Zuckerburg appear before them and address the issues and were not impressed with how it was handled, making mention of their favor towards the break-up of the monopoly."),
        ("p","On top of that, the industry was rapidly changing as fierce competition ripped away market share, most notably being TikTok. The proliferation of short-form content was something they fought against through the implementation of Reels. While the reels segment lags behind TikToks engagement rates, Instagram overall has a mature and robust advertising infrastructure with better conversion, click-through, and return on ad spend. This exemplifies their importance in Facebook's portfolio holdings, since the ability to copy competitors only works due to their large user-base and preferable advertising infrastructure. What does all this mean? Facebook is on a countdown to a trial which could result in the divestment of their most productive segment and main defense against competitors. Their acquisitive nature cannot sufficiently cushion the risk they face since every acquisition they pursue is under intense regulatory scrutiny to ensure competition remains unhindered. This leaves just one option still open."),
        ("i","From Social Media to The Metaverse"),
        ("p","This brings them to a pivotal moment in their life cycle, where they began betting on the idea of the Metaverse. The Metaverse is a virtual world accessible through the internet where users can do things like go to an office and work, hang out in a park, and other things that are normally done in person like going to a concert. Second Life, one of the most popular realized Metaverses, allowed characters to do these things while playing as cartoon versions of themselves and even let users speculate on their digital real estate. People were spending ~$100M per year on purchases within the world with some having well over $1M worth of virtual real estate holdings. The rationale for the Oculus acquisition was to make it applicable to more social gathering like what was mentioned above, a far cry from their initial value proposition of gaming. However, competition from the broader gaming segment like Sony’s VR headset which was made for Playstation and lackluster demand for online social gathering applications like mentioned above made it difficult for their products to gain any traction. "),
        ("i","m-2"),
        ("p","When all hope seemed lost for their VR vision, the pandemic presented a unique opportunity for the business. Speculative trading activity was at its highest through a swift recovery in the markets, after the blow dealt by lockdown led people towards making money from home. At the same time, cryptocurrency was in the greatest bull run in its history and everyone was trying to get out ahead of any new trend which could make money. These tailwinds put Oculus at the forefront of their new envisioned future. In 2021, Facebook committed itself to this shift by changing the parent company name to Meta Platform. The shift was a big piece of news to take the heat off and put them in a new light. Google did the same thing in 2015 by restructuring themselves under a new parent company called Alphabet to differentiate its search engine from the multitude of other ventures it has underway. The Facebook name change is indicative of a fundamental shift towards their prioritization of the Metaverse within their business model. "),
        ("p","While their Metaverse plans were in development, new headwinds came along with Apple's new privacy laws taking a bite into the Facebook social media segment projected advertising revenue. At the time, this was a massive deal for the entire app store with nearly every company losing 15% to 20% of their total advertising income and Facebook losing over $10B of revenue. The tracking came in the form of collecting user data on other websites to determine search patterns to help optimize targeted ads but Apple implemented an update in iOS 14 which forces the apps to ask permission in whether they would like to be tracked and people turning it off  created overall lower quality targeted ads. Zuckerberg publicly denounced the new policy implementation in a press release but mentioned that the company would be able to navigate the challenges due to their long-term investments. The company had been recently testing out a new application which was invite-only for a period in which users who had VR Headsets could collaborate with other users in practical manners (I.E. having virtual meeting rooms, whiteboards, etc.) and after some fine-tuning, the app known as Horizon Worlds was released to the public."),
        ("s","Present Day"),
        ("p","That brings us to today, where Meta Platforms is facing one of its biggest dilemmas with its foundational and growth-oriented value propositions, and is now on the clock to find a way to innovate or fall victim to their headwinds. These significant investments into the Metaverse and fundamental shift towards the prioritization of its success needs to work out for the company because the Facebook and Instagram services still are facing massive pressure to be broken up by the FTC. With Instagram being the leading service provider among the two with the greatest amount of growth and composition of total revenue, this would leave the parent company in practically irresolvable turmoil without anything to fall back on. With the potential loss of their flagship social media staples, we need to understand better what it is they’re falling back on and the feasibility of their vision in the Metaverse.  "),
        ("i","m-3"),
        ("s","The Vision & Goal"),
        ("p","Meta’s goal with this shift is pursuing what's called the Infrastructure Control Model, where they essentially control the hardware infrastructure as a proprietary entry point for users but can easily shift to other content providers, just like an iPhone. On top of that, they’re looking to develop a creator economy to attract and retain users in the application which cannot be accessed anywhere else due to its tech specifications with their headsets. In an ideal world, demand for the various services and products would be similar to that of the in-real-life alternatives and they would make a fee on every single transaction that occurs (on those concerts, real estate purchases, etc.). "),
        ("p","No long-term outlook as to what they consider success has been provided beyond short-term guidance for 2022 and their results. At the beginning of the year, Horizon Worlds hit a 300,000 user milestone and by the end had only 200,000 Horizon Worlds hit a 300,000 user milestone and by the end had only 200,000 Monthly Active Users (MAU) with the projected users being 500,000. They also found that only 9% of the 10,000 built worlds were ever visited by more than 50 users. These statistics show that while growth is a big part of their problem, retention of users needs to be considered as well. The marketing for the product has also seemingly been unsuccessful since there's a large disparity between groups of internet users who’ve have heard about horizon worlds and those who haven’t:"),
        ("i","m-4"),
        ("p","The underperformance is attributable to their value proposition. While other successful VR/M-World companies tend toward the gaming experiences, Meta’s betting on the social first vision tethered to real-world experiences which allows other companies like Sony to penetrate the market deeper as they capitalize off their gaming infrastructure. On top of all this, the biggest reason investors are against the venture is their inability to monetize Horizon World which makes it a cash-burner with bad unit economics and generally no robust demand. Back in 2021, they had broadly defined what success looked like to them with their Metaverse expansion:"),
        ("i","m-5"),
        ("p","The goal of hosting $100B+ of digital commerce and 1B people on their platform helps to define what their idea of success looks like, but can they achieve this? To understand that better, it makes sense to define some of the market's current dynamics, how those are expected to evolve over time, and where Meta fits into that bigger picture. Within the Meta Platforms realm, the Metaverse can be defined as the cumulation of three big drivers; the AR/XR utilization, the 3D elements, and the infrastructure required to host successful metaverses.  "),
        ("p","The AR/XR application has been pursued through the creation of their Meta Quest 2 headset. While it isn’t necessary to purchase the Meta Quest headset to access Horizon Worlds, that is a significant driver in the advancement of monetization through targeted advertising. By tracking user movements, Meta Quest users can be identified with 95% accuracy. In the capturing of this biomechanical data, it can near instantaneously create equivalent ROAS metrics for applications with access to it. Furthermore, it can predict your habits, understand your vulnerabilities, and create a much more granular marketing profile with the sole intent of attention gatherings, all of which can easily attract and retain new advertisers."),
        ("p","The 3D elements of the Metaverse bifurcate the different existing types of metaverses and are complemented with the AR/VR capabilities. Games like Minecraft and Roblox can be defined as Metaverse in-themselves, yet are fundamentally different as they operate in a 2D world. They’re economic success can be attributed to their prioritization of the experiential layer. User experiences are the biggest drivers of a successful 3D World and without it, capitalistic interests cannot be pursued. Meta significantly lacks from this perspective since Horizon Worlds is reportedly filled with bugs, low quality visuals, and an overall lacking things to do. The experiential layer is only successful thanks to Meta Quests ability to connect to PC games, which are third-party developed and released."),
        ("p","The most complicated piece of them all is the infrastructure layer of Metaverse development. The existing technology stack is too underdeveloped (or nonexistent) to help developers build more scalable and overall better AR/VR applications. In the same way that cloud libraries filled with photos or work is stored on a server owned by a large company, the Metaverse is going to require the same thing except will need over 1000x more computing power, speed, and storage than currently being used. With the industry being in its early stage, one way Meta’s addressing the issue is through perusal of strategic partnerships. For example, Meta  partnered with NVIDIA to expand their technical infrastructure and components required to sustain the M-World. "),
        ("i","m-6"),
        ("s","Future Considerations"),
        ("p","The industry is highly fragmented and that opens the door to consolidation as large players' roles become more defined. They’ll have the capital to either commit to companies who will lead the creation of these specialized projects or acquire them as a means to penetrate the market. There are a few issues which arise with Meta Platforms doing this; namely their time constraint due to the lawsuit with regulators, the specialized nature of the industry conflicting with their vision, and major ethical and regulatory implications. "),
        ("p","Their value proposition being oriented towards connecting communities conflicts with other industries like infrastructure development or medical simulations where that is not a priority. For Meta Platforms to succeed, they may need to broaden their vision and their shift towards the Metaverse and away from social media.  The development of infrastructure is expected to decrease in cost thanks to newer technologies like AI (and is something the company has begun to develop). Companies with the technical capabilities to complete the project could be acquired by Meta Platforms to bring these projects to life."),
        ("p","The one piece which will play a much bigger role as things progress is the ethical and regulatory considerations. Currently, the regulatory environment is heavily lagging but research is being done regarding policy to determine the best next steps. Meta Platforms has historically had issues regarding data trading and access to more sensitive information through AR/VR headset usage. Global regulatory organizations deal with these dilemmas differently, some on a continent-wide basis and some down to local levels, but the consensus is that if the ethical dilemmas aren’t considered seriously, irreversible damage can be done. With increasing fraudulence on the Facebook website, a lack of priority towards the ethical considerations would open the company to new headwinds going forward if they don’t find a way to align shareholder, customer and their own values."),
        ("i","m-7"),
        ("s","Conclusion"),
        ("p","The future of Meta Platforms and its various services is hazy at best but this transitionary period will be one that defines them going forward. In the short-term, their focus should be on refining the experiential layers of their product offering since this is the easiest to implement. They could also continue developing partnerships among industry leaders and smaller players to get their foot into the doors of sub-niches they expect to grow and can serve through resource provision or through an acquisition. The issue with this is the amount of time it would take to acquire and integrate the company and realize synergies which would conflict with the count-down of their lawsuit with the FTC."),
        ("p","While the business historically has been considered a social media company, this situation may give them the chance to reorient themselves in a different direction. If the business walks away from the lawsuit unscathed, they could see unequivocal success thriving in two industries with significant markets. If they fail to integrate the Metaverse solutions in time and the lawsuit forces a divestment in Instagram, Meta Platforms would remain a shell of its former self. Only time will tell the results, but one thing certain is that these next couple years will define the company going forward."),
    ],
}

tesla = {
    'edition':'fall-2022',
    'title':'Tesla: The Future of the Electrical Industry',
    'sh':'t', # shorthand 
    'img_dir':'tesla',
    'content':[
        ("s","Introduction"),
        ("p","The energy transition from fossil fuels to renewable power is one of the most talked about topics in today’s discourse, and for a good reason. The world is already experiencing the effects of climate change, whether it be through the increasing frequency and severity of natural disasters, or rising sea levels threatening the entire existence of several Pacific islands, or the increased difficulty of growing crops in increasingly hot and arid regions. Of course, where there is opportunity, there will be entrepreneurs who find a way to capitalize on it. One such entrepreneur who capitalized on the threat posed by climate change is Elon Musk, who helped fund Tesla at its early stages and eventually was appointed CEO after quite a bit of chaos amongst the rank and file of the company. Tesla started out as just an Electric Vehicle (EV) company, but their overall mission has always been to accelerate the advent of sustainable transportation, through their other business ventures, such as solar panels. This was made evident with their merger with SolarCity, operating charger stations, as well as the building of its battery storage capabilities. In general, Tesla has bucked the trend of most auto giants, who mostly outsource to contractors, by increasing its level of vertical integration to 80%, according to a Goldman Sachs analyst. While there have been integration challenges in this regard, the company continues to make progress in becoming a more integrated producer of electric vehicles."),
        ("p","Now, Tesla has done quite a bit to try to bring electric vehicle production in-house. They produce the batteries within their cars themselves, and have also inked offtake agreements with lithium producers, which allow them to have more or less a guaranteed flow of lithium for the years to come. However, there is significant potential for Tesla to take everything several steps further. As of now, Tesla’s main focus is mostly on cementing its place as one of the world’s pre-eminent electric vehicle producers. However, an electrified future relies more on bolstering the electric grid in its entirety, rather than just churning out electric vehicles en masse - this is one of the biggest challenges faced in the energy transition. As this article will show, Tesla can replicate its vertically integrated model to expand to the broader electrical infrastructure industry through its Tesla Energy segment, a space which presents a massive market opportunity for the company to scale up within."),
        ("s","The Declining Power Grid"),
        ("p","It’s no secret that America’s infrastructure is falling apart. According to the White House, public infrastructure spending relative to GDP has fallen by over 40% since the 1960s. Moreover, 20% of America’s roads and over 45,000 bridges are in disrepair. A large portion of America’s water supply still relies on dangerous and toxic lead pipes."),
        ("p","Many of these infrastructural concerns apply to the electric grid as well. The average lifespan of transmission lines is 50 years. Most of America’s transmission lines are over 40 years old, and according to Swiss Re, malfunctions tend to escalate during this time. As over 90% of America’s power grid relies on these transmission lines, our reliance on this system does not bode well for the future."),
        ("i","t-1"),
        ("p","However, this isn’t the worst of it. The data used by the operators of this infrastructure to make major decisions relies on past data which doesn’t factor in climate change, which means that the country’s electric grid isn’t equipped to tackle the challenges brought on by climate change. To make matters worse, as demand for electricity spikes due to the proliferation of electric vehicles, the grid has already shown weakness. A heatwave, which knocked out several power plants in Texas earlier this year, forced Texans to limit electricity from vital services, such as air conditioning. Similarly, California asked residents to stop charging their EVs due to climate conditions at the same time that the state was mulling EV adoption and instituting bans on internal combustion engine cars."),
        ("p","This situation further does not consider another issue laying between the intersection of electric vehicles and the power grid - what good are electric vehicles if the electricity used to charge them is produced from dirty energy? Despite growing interest in renewable energy sources, such as wind and solar power, there remains the issue of intermittency. For example, wind power generates electricity mostly during the earliest and latest hours of the day. Due to poor renewable energy storage infrastructure across the world, this means that excess energy is generated during these times, when there is often less demand, and thus must be “dumped” for free. This limits the ability to actually scale renewable energy; however, large scale battery energy storage solutions offer a solution to this. That being said, actual penetration of BESS systems is quite low across the world, meaning there will need to be significant capital expenditure required on this front."),
        ("p","Clearly, for the energy transition to actually go through, there will need to be trillions of dollars spent refurbishing the country’s infrastructure. Currently, there is already a lot of infrastructure funding surrounding the power grid. President Biden’s Bipartisan Infrastructure Deal outlines the government’s plans to invest more than $65 billion to upgrade our power infrastructure by building new transmission lines and the funding of new programs to support the development of clean energy technologies. In addition to this, this legislation will accelerate widespread adoption of electric vehicles through investing $7.5 billion to create a national network of EV chargers throughout America. This provides huge opportunities for companies with expertise in the area of electric power to obtain billions of dollars worth of contracts to upgrade America’s infrastructure, then accessing massive annuity-like contracts to maintain it. Tesla, by virtue of its vertically integrated nature encompassing power generation, power storage, and manufacturing the end products of EVs, is in a unique position to forge the partnerships needed to equip itself to fill this gap and cement a position for itself within the broader infrastructure space."),
        ("s","Tesla’s Expertise"),
        ("p","Tesla is highly knowledgeable in the electrical industry due to its subsidiary, Tesla Energy. Originally known as SolarCity, Tesla acquired the clean energy company in 2016, where they mainly focused on the sale of solar panels for homeowners. Tesla Energy has since launched three products: the Solar Roof, the Powerwall, and most recently, the Megapack. Functioning similar to traditional solar panels, the Solar Roof is essentially solar panels seamlessly integrated into roofs through combining glass solar tiles with steel roofing tiles. Tesla’s Powerwall is a battery storage solution that allows homeowners to store excess solar energy. Lastly, the Megapack is a similar energy storage product to the Powerwall, just on a larger scale for commercial projects. In fact, energy storage is something that Tesla has begun to hone in on more, with the company’s overall mission statement being “to accelerate the world’s transition to sustainable energy”. In 2021, Tesla began building a production facility that will be able to produce 40 million kWh of energy storage per year in Austin, Texas. An average home in America uses 10,632 kWH of energy a year, meaning that this would be able to power 3762 houses."),
        ("i","t-2"),
        ("p","In addition to this expansion, Tesla reports that energy storage and solar panel deployment has grown 62% and 13% respectively in the third quarter of 2022. An emphasis on cross-selling solar power installations with the Powerwall and making products more widely available increased Tesla Energy revenues to $1.117 billion, a 38.6% year-over-year increase during the third quarter of 2022. These developments are crucial for Tesla in both solving key problems of tempermental power grids, and in expanding in the energy storage market."),
        ("p","Tesla has used their expertise in energy storage to offer timely support for the US in times of need. For example, in 2021 when Hurricane Ida hit the New Orleans area the power grid was shut down and became inoperable for several weeks. Tesla was able to provide power to over 1,000 people by deploying powerwalls and solar panel disaster relief systems. With proven capabilities in the electrical industry, Tesla can look to provide more long-term energy storage solutions to American consumers, and even more importantly, to renewable energy projects which can make use of Tesla’s capabilities in battery energy storage solutions. By storing excess energy instead of having to dispatch it, the economics on renewable energy development projects will increase, which incentivizes further construction of renewable capacity, which benefits the nation from an energy transition perspective, and the consequent demand for even more energy storage, which benefits Tesla. Currently in Texas, Tesla is piloting a service where selected Powerwall users can sell the energy generated from their solar panels back to the power grid. Furthermore, they have created their own utilities company, Tesla Energy Ventures and gained approval to set up a Virtual Power Plant in Texas. This is a method where Tesla can draw energy from all individual batteries to the grid which eliminates the need for natural gas fire beaker plants during periods of high energy demand. So far, these developments are promising indicators of Tesla’s ability to venture into sustainable energy storage for consumers all over the US."),
        ("s","The Critical Metals"),
        ("p","Now, further expansion into this space is easier said than done. If Tesla is to move into larger scale development of energy storage solutions and electric transmission infrastructure, this will mean that its cost structure will tilt towards relatively volatile commodity prices, such as copper. Tesla has already been working on hedging out its risks through offtakes and potentially outight acquisitions of lithium projects. However, the raw materials needed in this proposed transformation would be on a whole different level."),
        ("p","Some of the key metals needed in this scenario include copper, lithium, and nickel. These three all have quite interesting situations. Copper production is most concentrated within South America, the US, and Russia, with a relatively mature production profile. Lithium, on the other hand, is a bit more nascent in the sense that most production occurs in Australia or South America, but there are a massive flurry of development projects underway worldwide, including within the US and Canada. Nickel is another metal which has been receiving increased attention due to its importance in batteries and also within the wind industry - Indonesia is the dominant producer worldwide."),
        ("p","Acquiring battery metal mines is a strategic move that can help Tesla achieve more vertical integration and control over costs. By owning the mines, Tesla can secure a steady supply of critical components, reduce dependence on external suppliers, and increase control over the supply chain. In this section, we will take a look at four key battery metals: lithium, cobalt, nickel, and copper, and examine the potential benefits and costs of acquiring mines for Lithium is a crucial component in lithium-ion batteries, which are used in electric vehicles. As demand for electric vehicles continues to rise, the demand for lithium is also expected to increase significantly. Some of the main lithium mines are located in countries like Australia, Chile, and Argentina; however, there are an increasing number of lithium projects under development in both North America and Europe, which are closer to Tesla’s gigafactories in the US and Germany. Nickel is another important metal for battery production and is used in the cathode of lithium-ion batteries. Mines for nickel can be found in Canada, Russia, and Indonesia, among other nations. Due to the high concentration of production from more geopolitically volatile nations like Russia and Indonesia, it makes sense for Tesla to acquire mines and help finance their expansion to lock in supply. Finally, copper is used in the wiring of electric vehicles and is important for both battery production and broader electric infrastructure. Mines for copper can be found in countries such as Chile, Peru, and China. Therefore, by Tesla acquiring these battery metal mines, it will achieve vertical integration, have a steady supply of key components, and reduce dependence on external suppliers."),
        ("s","Conclusion"),
        ("p","Tesla has the potential to leverage its business model to expand to the broader electrical industry through placing bigger importance on its Tesla Energy segment. Tesla, unlike other electrical vehicle companies, has already expanded their operations in the electricity generating and storing industry through their solar panels and batteries. Furthermore, acquiring the  mines is a crucial part in furthering their expansions, as Tesla gains significant advantages in reducing the overall costs of production, and increased control over its products and services. Of course, there will be arguments that Tesla does not have the expertise to operate mines - while this is true, it is also mitigated by the fact that Tesla can just keep the same management in place and act as a more passive manager. There are several non-specialized global conglomerates with mining operations, such as Sumitomo, which sets a precedent that non-mining companies can own mines."),
        ("p","Using their expertise, access to valuable materials, and knowing the deteriorating power grid in America, Tesla has significant financial gain to make through forming partnerships to improve and create new infrastructure that will ultimately reduce Americans' reliance on the outdated and faulty power grid system. In conclusion, as the electrical industry continues to evolve with an emphasis on renewable energy supported by the government, and the popularization of electrical vehicles, Tesla is in the perfect position with their resources to be at the forefront of the future electrical industry."),
    ],
}


def generate_body(paper):
    edition = paper['edition']
    title = paper['title']
    sh = paper['sh']
    img_dir = paper['img_dir']
    content = paper['content']

    with open('utils/output/file.txt', 'w', encoding='utf-8') as f:
        # header
        f.write('<!-- Post Details Stat -->\n')
        f.write('<div class="post-details pb-80">\n')
        f.write('<div class="container">\n') 
        f.write('<div class="row">\n') 
        f.write('<div class="col-lg-8">\n') 
        f.write('<div class="about-details-cap">\n') 
        f.write(f'<h2>{title}</h2>\n') 
        f.write('</div>\n') 
        f.write('</div>\n') 
        f.write('<div class="col-lg-10">\n') 
        f.write('<div class="about-details-cap">\n') 

        # content

        img_count = 1

        for line in content:
            if line[0] == 's':
                f.write(f'<p class="mb-30"><b>{line[1]}</b></p>\n')
            elif line[0] == 'i':
                f.write(f'<div class="details-img">\n')
                f.write(f'<img class="img-fluid mb-15" src="assets/img/{edition}/articles/{img_dir}/{sh}-{img_count}.png" alt="" style="vertical-align:top;margin:10px 0px; max-height: 500px">\n')
                f.write(f'</div>\n')

                img_count += 1
            elif line[0] == 'p':
                f.write(f'<p class="mb-30">\n{line[1]}\n</p>\n')

        # footer
        f.write('</div>\n') 
        f.write('</div>\n') 
        f.write('</div>\n') 
        f.write('</div>\n') 
        f.write('<!-- Post Details End -->\n') 
 
if __name__ == '__main__':

    generate_body(meta)



